language: node_js
node_js:
  - "15"
# cache:
#   directories:
#     - node_modules
script:
  - yarn test
  - yarn build
after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
